include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: true 
    avoid_print: true 
    close_sinks: true 
    empty_catches: true
    null_closures: true 
    package_names: true 
    hash_and_equals: true
    prefer_contains: true
    prefer_is_empty: true
    unnecessary_new: true
    avoid_empty_else: true
    avoid_void_async: true
    camel_case_types: true
    empty_statements: true
    throw_in_finally: true
    unnecessary_this: true
    unnecessary_late: true
    recursive_getters: true
    only_throw_errors: true
    unawaited_futures: true
    unnecessary_const: true
    avoid_init_to_null: true
    await_only_futures: true
    eol_at_end_of_file: true
    directives_ordering: true
    prefer_final_locals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_not_empty: true
    prefer_void_to_null: true
    secure_pubspec_urls: true
    use_named_constants: true
    avoid_returning_this: true
    cancel_subscriptions: true
    prefer_single_quotes: true
    camel_case_extensions: true
    avoid_final_parameters: true
    prefer_is_not_operator: true
    unnecessary_statements: true
    control_flow_in_finally: true
    prefer_relative_imports: true
    empty_constructor_bodies: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_final_in_for_each: true
    prefer_if_null_operators: true
    sized_box_for_whitespace: true
    constant_identifier_names: true
    omit_local_variable_types: true
    avoid_relative_lib_imports: true
    list_remove_unrelated_type: true
    always_declare_return_types: true
    avoid_escaping_inner_quotes: true
    prefer_initializing_formals: true
    avoid_unnecessary_containers: true
    avoid_returning_null_for_void: true
    avoid_return_types_on_setters: true
    depend_on_referenced_packages: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    prefer_null_aware_method_calls: true
    unnecessary_to_list_in_spreads: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    avoid_catches_without_on_clauses: true
    avoid_renaming_method_parameters: true
    iterable_contains_unrelated_type: true
    literal_only_boolean_expressions: true
    avoid_types_on_closure_parameters: true
    unnecessary_string_interpolations: true
    avoid_positional_boolean_parameters: true
    unnecessary_brace_in_string_interps: true
    avoid_multiple_declarations_per_line: true
    unnecessary_null_in_if_null_operators: true
    use_if_null_to_convert_nulls_to_bools: true
    null_check_on_nullable_type_parameter: true
    avoid_null_checks_in_equality_operators: true
    curly_braces_in_flow_control_structures: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_interpolation_to_compose_strings: true
    always_put_required_named_parameters_first: true
    no_leading_underscores_for_local_identifiers: true
    avoid_single_cascade_in_expression_statements: true
    avoid_bool_literals_in_conditional_expressions: true
    
