name: movies_app
description: See and favorite movies.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Remote Data
  dio: ^5.1.1

  # UI
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0

  # Utils
  get_it: ^7.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
